### ISSUE TITLE
Random crash - Linux

### ISSUE THREAD

**Issue by talamortis** [azerothcore/mod-vas-autobalance#2]
Intermittent crash on Linux system - Do not know whats causing it as im on windows and my server is Linux based. could do with more testing

**Comment by Yehonal** [comment]
Could you compile with RelWithDebugInfo? So you can check what causes the
crash with gdb

Il 28 Feb 2018 10:16 PM, "Lee" <notifications@github.com> ha scritto:

Intermittent crash on Linux system - Do not know whats causing it as im on
windows and my server is Linux based. could do with more testing

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/azerothcore/mod-vas-autobalance/issues/2>, or mute the
thread

**Comment by Yehonal** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/a36e94a49a5b3bbdf01c622600c87da8cf55a26b
